In [1]:
%load_ext autoreload
%autoreload 2

import tqdm, sys, os, time, logging, warnings
from numba.core.errors import NumbaDeprecationWarning, NumbaPendingDeprecationWarning
warnings.simplefilter('ignore', category=NumbaDeprecationWarning)
warnings.simplefilter('ignore', category=NumbaPendingDeprecationWarning)

import pandas as pd
import numpy as np
import scipy as sp
import scipy.sparse as sps

import scanpy as sc
import anndata as ad
import muon as mu
import scvi

import plotly.express as px
import plotly.graph_objects as go
# sc.set_figure_params(dpi=100, fontsize=10, figsize="8,8", color_map='viridis', transparent=True)
from sklearn.metrics import adjusted_rand_score as ari

Global seed set to 0


# Load

In [2]:
mdata = mu.read_h5mu("data/processed/scRNAseq_snRNAseq_filteredQC_processedPCA.h5mu")
scrna = mdata['scrna']
snrna = mdata['snrna']

mdata.X = sps.vstack([mdata['scrna'].X, mdata['snrna'].X])
mdata

MuData object with n_obs × n_vars = 258555 × 31053
  obs:	'class_label', 'cluster_color', 'cluster_id', 'cluster_label', 'gene.counts', 'size', 'subclass_label', 'umi.counts', 'dataset'
  var:	'highly_variable'
  uns:	'neighbors', 'umap'
  obsm:	'X_pca', 'X_umap'
  obsp:	'connectivities', 'distances'
  2 modalities
    scrna:	74132 x 31053
      obs:	'Amp_Date', 'Amp_Name', 'Amp_PCR_cyles', 'Cell_Capture', 'Donor', 'Gender', 'Lib_Cells', 'Lib_Date', 'Lib_Name', 'Lib_PCR_cycles', 'Lib_PassFail', 'Lib_type', 'Live_Cells', 'Live_percent', 'Mean_Reads_perCell', 'Median_Genes_perCell', 'Median_UMI_perCell', 'Region', 'Replicate_Lib', 'Saturation', 'Seq_batch', 'Total_Cells', 'aggr_num', 'class_label', 'cluster_color', 'cluster_id', 'cluster_label', 'doublet.score', 'exp_component_name', 'gene.counts', 'library_id', 'mapped_reads', 'method', 'nonconf_mapped_reads', 'size', 'subclass_label', 'total.reads', 'tube_barcode', 'umi.counts', 'unmapped_reads', 'dataset'
      var:	'gene_id', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
      uns:	'hvg', 'log1p', 'neighbors', 'pca', 'umap'
      obsm:	'X_pca', 'X_umap', 'counts'
      varm:	'PCs'
      obsp:	'connectivities', 'distances'
    snrna:	184423 x 31053
      obs:	'Allen.class_label', 'Allen.cluster_color', 'Allen.cluster_id', 'Allen.cluster_label', 'Allen.subclass_label', 'Broad.QC.Mito', 'Broad.QC.doublet', 'Broad.passQC', 'Comb.QC', 'MALE', 'QC', 'cl', 'class_label', 'cluster', 'cluster_color', 'cluster_id', 'cluster_label', 'comb.QC', 'dataset', 'gene.counts', 'nGene', 'nUMI', 'size', 'subclass_label', 'umi.counts'
      var:	'gene_id', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
      uns:	'hvg', 'log1p', 'neighbors', 'pca', 'umap'
      obsm:	'X_pca', 'X_umap', 'counts'
      varm:	'PCs'
      obsp:	'connectivities', 'distances'

In [3]:
mdata.X[:5, :5].todense()

matrix([[3.7340188 , 0.        , 0.        , 0.        , 0.        ],
        [2.933109  , 0.        , 0.        , 0.        , 0.        ],
        [3.1178575 , 0.414911  , 0.        , 0.        , 0.        ],
        [3.3489263 , 0.        , 0.        , 0.38774753, 0.        ],
        [3.7994354 , 1.0549483 , 0.        , 0.        , 0.        ]],
       dtype=float32)

In [4]:
scrna.X[:5, :5].todense()

matrix([[3.7340188 , 0.        , 0.        , 0.        , 0.        ],
        [2.933109  , 0.        , 0.        , 0.        , 0.        ],
        [3.1178575 , 0.414911  , 0.        , 0.        , 0.        ],
        [3.3489263 , 0.        , 0.        , 0.38774753, 0.        ],
        [3.7994354 , 1.0549483 , 0.        , 0.        , 0.        ]],
       dtype=float32)

In [5]:
scrna.obsm['counts'][:5, :5].todense()

matrix([[49.,  0.,  0.,  0.,  0.],
        [14.,  0.,  0.,  0.,  0.],
        [42.,  1.,  0.,  0.,  0.],
        [58.,  0.,  0.,  1.,  0.],
        [70.,  3.,  0.,  0.,  0.]], dtype=float32)

In [6]:
scrna

AnnData object with n_obs × n_vars = 74132 × 31053
    obs: 'Amp_Date', 'Amp_Name', 'Amp_PCR_cyles', 'Cell_Capture', 'Donor', 'Gender', 'Lib_Cells', 'Lib_Date', 'Lib_Name', 'Lib_PCR_cycles', 'Lib_PassFail', 'Lib_type', 'Live_Cells', 'Live_percent', 'Mean_Reads_perCell', 'Median_Genes_perCell', 'Median_UMI_perCell', 'Region', 'Replicate_Lib', 'Saturation', 'Seq_batch', 'Total_Cells', 'aggr_num', 'class_label', 'cluster_color', 'cluster_id', 'cluster_label', 'doublet.score', 'exp_component_name', 'gene.counts', 'library_id', 'mapped_reads', 'method', 'nonconf_mapped_reads', 'size', 'subclass_label', 'total.reads', 'tube_barcode', 'umi.counts', 'unmapped_reads', 'dataset'
    var: 'gene_id', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'hvg', 'log1p', 'neighbors', 'pca', 'umap'
    obsm: 'X_pca', 'X_umap', 'counts'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

# SCVI

In [7]:
mdata.obs

scrna:Amp_Date   
sample_name                                                   
AAACCCAAGCTTCATG-1L8TX_181211_01_G12             11/29/2018  \
AAACCCAAGTGAGGTC-1L8TX_181211_01_G12             11/29/2018   
AAACCCACACCAGCCA-1L8TX_181211_01_G12             11/29/2018   
AAACCCAGTGAACGGT-1L8TX_181211_01_G12             11/29/2018   
AAACCCAGTGGCATCC-1L8TX_181211_01_G12             11/29/2018   
...                                                     ...   
pBICCNsMMrMOpRMiM006d190320_TTTGGTTCATGAGTAA            NaN   
pBICCNsMMrMOpRMiM006d190320_TTTGGTTTCGCAAGAG            NaN   
pBICCNsMMrMOpRMiM006d190320_TTTGTTGAGACTCTTG            NaN   
pBICCNsMMrMOpRMiM006d190320_TTTGTTGTCACCTTGC            NaN   
pBICCNsMMrMOpRMiM006d190320_TTTGTTGTCATGCTAG            NaN   

                                                  scrna:Amp_Name   
sample_name                                                        
AAACCCAAGCTTCATG-1L8TX_181211_01_G12          A8TX_181129_03_A03  \
AAACCCAAGTGAGGTC-1L8TX_181211_01_G12          A8TX_181129_03_A03   
AAACCCACACCAGCCA-1L8TX_181211_01_G12          A8TX_181129_03_A03   
AAACCCAGTGAACGGT-1L8TX_181211_01_G12          A8TX_181129_03_A03   
AAACCCAGTGGCATCC-1L8TX_181211_01_G12          A8TX_181129_03_A03   
...                                                          ...   
pBICCNsMMrMOpRMiM006d190320_TTTGGTTCATGAGTAA                 NaN   
pBICCNsMMrMOpRMiM006d190320_TTTGGTTTCGCAAGAG                 NaN   
pBICCNsMMrMOpRMiM006d190320_TTTGTTGAGACTCTTG                 NaN   
pBICCNsMMrMOpRMiM006d190320_TTTGTTGTCACCTTGC                 NaN   
pBICCNsMMrMOpRMiM006d190320_TTTGTTGTCATGCTAG                 NaN   

                                              scrna:Amp_PCR_cyles   
sample_name                                                         
AAACCCAAGCTTCATG-1L8TX_181211_01_G12                         12.0  \
AAACCCAAGTGAGGTC-1L8TX_181211_01_G12                         12.0   
AAACCCACACCAGCCA-1L8TX_181211_01_G12                         12.0   
AAACCCAGTGAACGGT-1L8TX_181211_01_G12                         12.0   
AAACCCAGTGGCATCC-1L8TX_181211_01_G12                         12.0   
...                                                           ...   
pBICCNsMMrMOpRMiM006d190320_TTTGGTTCATGAGTAA                  NaN   
pBICCNsMMrMOpRMiM006d190320_TTTGGTTTCGCAAGAG                  NaN   
pBICCNsMMrMOpRMiM006d190320_TTTGTTGAGACTCTTG                  NaN   
pBICCNsMMrMOpRMiM006d190320_TTTGTTGTCACCTTGC                  NaN   
pBICCNsMMrMOpRMiM006d190320_TTTGTTGTCATGCTAG                  NaN   

                                              scrna:Cell_Capture scrna:Donor   
sample_name                                                                    
AAACCCAAGCTTCATG-1L8TX_181211_01_G12                      5898.0      426003  \
AAACCCAAGTGAGGTC-1L8TX_181211_01_G12                      5898.0      426003   
AAACCCACACCAGCCA-1L8TX_181211_01_G12                      5898.0      426003   
AAACCCAGTGAACGGT-1L8TX_181211_01_G12                      5898.0      426003   
AAACCCAGTGGCATCC-1L8TX_181211_01_G12                      5898.0      426003   
...                                                          ...         ...   
pBICCNsMMrMOpRMiM006d190320_TTTGGTTCATGAGTAA                 NaN         NaN   
pBICCNsMMrMOpRMiM006d190320_TTTGGTTTCGCAAGAG                 NaN         NaN   
pBICCNsMMrMOpRMiM006d190320_TTTGTTGAGACTCTTG                 NaN         NaN   
pBICCNsMMrMOpRMiM006d190320_TTTGTTGTCACCTTGC                 NaN         NaN   
pBICCNsMMrMOpRMiM006d190320_TTTGTTGTCATGCTAG                 NaN         NaN   

                                             scrna:Gender  scrna:Lib_Cells   
sample_name                                                                  
AAACCCAAGCTTCATG-1L8TX_181211_01_G12                 Male           9733.0  \
AAACCCAAGTGAGGTC-1L8TX_181211_01_G12                 Male           9733.0   
AAACCCACACCAGCCA-1L8TX_181211_01_G12                 Male           9733.0   
AAACCCAGTGA

In [8]:
scvi.model.SCVI.setup_anndata(mdata, 
                              layer='counts', 
                              batch_key="sample_name", 
                              labels_key='subclass_label')


ValueError: Detected unpaired observations in modality scrna. Please make sure that data is fully paired in all MuData inputs. Either pad the unpaired modalities or take the intersection with muon.pp.intersect_obs().